spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/birzha?useSSL=false
        username: root
        password: root
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
    profiles:
      active: container
    redis:
      host: 172.10.10.236
      port: 6379
    application:
      name: auth-server
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
# --- server
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

#management:
#  endpoint:
#    metrics:
#      enabled: true
#    logfile:
#      enabled: true
#    shutdown:
#      enabled: false
#    info:
#      enabled: true

