version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: nikita9596/authorization_service:authorization_service
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
    - "8080:80"
    networks:
    - webnet
networks:
  webnet: