spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://prodex-replicatest.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?useSSL=false
        username: devprod
        password: Fh24soaf8sy3
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
    profiles:
      active: dev
    redis:
      host: localhost
      port: 6379
# --- server
server:
  port: 8080

#management:
#  endpoint:
#    metrics:
#      enabled: true
#    logfile:
#      enabled: true
#    shutdown:
#      enabled: false
#    info:
#      enabled: true
#  metrics:
#    enable: true
#    distribution:
#      percentiles-histogram: true
#      sla:
#        http.server.requests: 1ms,5ms

