spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev1?useSSL=false
        username: exdevdb
        password: KQmK82dd
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
    redis:
      port: 6379
      host: 172.10.10.236
# --- server
server:
  port: 8080


