spring:
  profiles:
    active: dev
  application:
    admin:
      enabled: true
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev1?useSSL=false
    username: exmicro
    ssm-path: /exrates/auth-service/dev/mysql.token
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  redis:
    host: 172.50.50.100
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.50.50.245:8090/eureka}
    should-unregister-on-shutdown: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS